### ISSUE TITLE
Create code block sprites

### ISSUE THREAD

**Issue by MarcusPeixe** [TP-Coltec-UFMG/CodeBot#5]
Edit and draw sprites (`.png`) for the code blocks.

### Note:

* See [this algorithm](https://en.wikipedia.org/wiki/9-slice_scaling) for reference. A similar method will be used for scaling code blocks as new elements are inserted inside them (i.e. for flow control structure blocks).
* The slices layout may change.

**Comment by CommonHooman** [comment]
xacumpai

**Comment by MarcusPeixe** [comment]
The sprites for simple code blocks have been created (simple rectangles with rounded corners). They demonstrate the power of the 9 slice algorithm well enough, but it will work even better for _repeat_ blocks.
